version: '3.3'

services:
  db:
    image: mongo:3.6
    container_name: mongodb
    volumes:
      - dbdata:/data/db
    restart: always
    ports:
      - "27017:27017"
    command: --storageEngine wiredTiger

  fpm:
    container_name: php7
    image: nanoninja/php-fpm:7.2
    ports:
      - "9000:9000"
    links:
      - db
    volumes:
      - "./:/var/www/html"

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - fpm
    volumes:
      - ".:/code"
      - "./etc/nginx:/etc/nginx/conf.d"

volumes:
  dbdata: